- name: install dispatch component
  hosts: dispatch
  become: 'yes'
  tasks:
    - name: Install GoLang
      ansible.builtin.yum:
        name: golang
        state: installed

    - name: check roboshop user exist or not
      ansible.builtin.command: id roboshop
      register: out
      ignore_errors: true

    - when: out.rc != 0
      name: create roboshop user
      become: 'yes'
      ansible.builtin.user:
        name: roboshop

    - name: check /app directory exist or not
      ansible.builtin.stat:
        path: /app
        register: directory

    - name: print directory stat
      ansible.builtin.debug:
        msg: 'output: {{directory}}'

    - when: directory stat.exist == False
      name: create /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download dispatch artifact
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
        dest: /tmp

    - name: extract dispatch artifact
      ansible.builtin.unarchive:
        src: /tmp/dispatch.zip
        dest: /app
        remote_src: 'yes'

    - name: Install Python 3.6
      ansible.builtin.user:
        name: '{{item}}'
        state: installed
      loop:
        - python36
        - gcc
        - python3-devel

    - name: copy file dispatch.service
      ansible.builtin.copy:
        src: dispatch.service
        dest: /etc/systemd/system/dispatch.service

    - name: daemon-reload
      ansible.builtin.systemd:
        daemon-reload: true
        
    - name: Start and enable dispatch service
      ansible.builtin.service:
        name: dispatch
        state: started
        enabled: 'yes'
