- name: install redis component
  hosts: redis
  become: 'yes'
  tasks:
    - name: disable MySQL 8 version
      ansible.builtin.command: yum module disable mysql -y

    - name: Copy file mongo.repo to yum.repos.d
      ansible.builtin.copy:copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mysql-community-server
      ansible.builtin.yum:
        name: mysql-community-server
        state: installed

    - name: Start and enable user service
      ansible.builtin.service:
        name: user
        state: started
        enabled: 'yes'

    - name: create mysql roboshop user password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
    
    - name: new password
      ansible.builtin.command: mysql -uroot -pRoboShop@1
