- name: install web component
  hosts: web
  become: 'yes'
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: installed

    - name: Start & Enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: remove html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download frontend content
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/web.zip
        dest: /tmp

    - name: Extract the frontend content
      ansible.builtin.unarchive:
        src: /tmp
        dest: /usr/share/nginx/html
        remote_src: 'yes'

    - name: Copy file roboshop.conf
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf
        
    - name: Restart Nginx using service module
      ansible.builtin.service:
        name: nginx
        state: restarted
